# Generated by Django 4.2.8 on 2023-12-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Name')),
                ('email', models.EmailField(max_length=70, verbose_name='Email')),
                ('password', models.CharField(max_length=70, verbose_name='Password')),
            ],
        ),
    ]
